package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, 13 May, 2026 11:24:26 PM IST
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float sub (float a, float b);
  float mul (float a, float b);
  float div (float a, float b);
} // interface CalculatorOperations
